#rm -r EVM/Atomicity/swapName 
#rm -r Ergo/SigmaParticle/swapName 
#rm -r swapName 
rm -r EVM/Atomicity/Initiator_swapName 
rm -r Ergo/SigmaParticle/Initiator_swapName 
rm -r Initiator_swapName 
rm -r EVM/Atomicity/Responder_swapName 
rm -r Ergo/SigmaParticle/Responder_swapName 
rm -r Responder_swapName 
